apiVersion: postgresql.cnpg.io/v1
kind: DatabaseRole
metadata:
  name: zitadel
  namespace: postgres-prod
spec:
  name: zitadel
  login: true
  cluster:
    name: postgres-prod
  passwordSecret:
    name: zitadel-user
  databaseRoleReclaimPolicy: retain
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: zitadel
  namespace: postgres-prod
spec:
  name: zitadel
  owner: zitadel
  cluster:
    name: postgres-prod
  databaseReclaimPolicy: retain
