apiVersion: v1
kind: Secret
metadata:
    name: authentik-user
    namespace: postgres-prod
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:Igz9Xal9B3mc,iv:OpxGDzSMWaFxoQXswhm726UBPXXBNi6eMmpiZRg7F7o=,tag:/NBdeyHq1BrN1TRJBUmeqg==,type:str]
    password: ENC[AES256_GCM,data:uGUkXIiS6pkmOa9LyoZEv1BIqs8pD/g++FPUzk5iVu4SPHL0FEEPQvrQa9fJDJaduDcTeVExQb5DPfaNSgCYwA==,iv:I73H/gLmq9123AIwswtetRU9MWisAEac3CNuOrjwu9I=,tag:hIdNlJbNZknUlMHuFc3zeQ==,type:str]
sops:
    age:
        - recipient: age13945fxf9dmg0sgmy9hteh5tuvlpz90hx3dqx63plf63f4zwhg9ysth6d98
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvdnMzNXM2TncvaDhZNUkr
            TG1UQjhKSmlMRDlnUGpsaGZWNW51OUZQbVZNCkdWM0lNekZocU5iT2FzSE9RQXZF
            T3p0L0RwY3lmTm1XRHo0TUhId3BYWGsKLS0tIGs4ZTV0Y2U2eWs1aHJud0NNTjBt
            bWF6Tmw5aFRiUzZpenIzR3NidDlKaE0KPfI8rp+L1+rEvO8rsrZ71e2rKYlExJui
            Bx9Xrjwun3NBOFecOz5tBi8S2+iFh3cwcPbmFbNXph3G1dwF3Qb2eg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-03T07:14:10Z"
    mac: ENC[AES256_GCM,data:ojK61IsgfEMvG9UuWv3uaZStB2tQTA7KC11D9UjZZgKSXMFJ/2+vewA1FILQuE2MlIxHRH4jqkgiATkoyWz8ujPwpJBW+uyUgI7vLACTq0tPmDkynzc8NMpK83NbBRLmAS/Onx/soVms32NpyK5dtahdoyJ5zIAUnZV1Lo+l1WI=,iv:M1gZMUqu+tksmPs5egVxoFi9VJSDdhw6OTuFJSIhdmc=,tag:+SuYfQMXfEG8YWTvntlXaA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
