apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: postgres-prod

resources:
  - 00-namespace.yaml
  - 10-cluster.yaml
  - 11-scheduled-backup.yaml
  - 20-litellm.yaml
  # Copier 20-database.example.yaml → 20-<app>.yaml pour créer une base.

generators:
  - ksops-generator.yaml
