##############################################################################
# Rôle applicatif LiteLLM. Éditer : sops applications/postgres-prod/litellm-user.secret.yaml
# Type basic-auth obligatoire (CNPG 1.30).
##############################################################################
apiVersion: v1
kind: Secret
metadata:
    name: litellm-user
    namespace: postgres-prod
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:5D+YiiVuig==,iv:Fq2akg40P9fxLNPvNiK06jY5fppkMlmHE1opoY9JS1Q=,tag:RVC1nMV2mLI0QnMD5gPiiA==,type:str]
    password: ENC[AES256_GCM,data:TzGbweMrP6EjCetaWDuf4LyyhWsBbNUEF4lUhDZvcYA=,iv:X5uPFKwc29z5Aec7qS0ZAuRxdJhr1M5wop7kV6flzDc=,tag:qMQNie01dIiKwp2VBkCyLA==,type:str]
sops:
    age:
        - recipient: age13945fxf9dmg0sgmy9hteh5tuvlpz90hx3dqx63plf63f4zwhg9ysth6d98
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTajl2YjhpcTBxZzVxZnA5
            VnNYMkRqZ0tqY09qbzh4SDh1YUUxU3dEWmdZCkFwNzQwOUg2UmJnSDhWY1M0MFVK
            cE9tajJ3QkxnLzdWTDNXSUs2ZHVGQVEKLS0tIDNJVU03MHAvZzBQdVdCa2QxVzh6
            QXAzTnFOcHY3Q3lwWUYydlVibW9LMGMKGTzGDKEUf0M3uOo8obTtkjlelBT5385l
            t9CpyI/6YSj8LH+GbLfUkklti7MXH6Z3DlXTCnl2GftrVJwCzbT71w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-28T06:40:40Z"
    mac: ENC[AES256_GCM,data:DjuYekM91ONywDzq7QKLRNVMmumI7IbeNcqkWM6pU/rGHSwaebmNd/RI8mhO/vLmCopTfXmeb+xgDeDqdjeAvsb8cIe3xu+islKSPAGcSflXx2EkZHCTLEY8mYsHwusKk5TWD7gJ0eDVQHO96oUOI0LCiq3iVCDSaQgupTSPF1M=,iv:2DKQxhloF8dWGkMCkAv9MNFXJRaFHYlDtklwIU7b53o=,tag:FfSAu2XMJ1Fv0esIXPAPHQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
