##############################################################################
# Rôle applicatif n8n. Éditer : sops applications/postgres-prod/n8n-user.secret.yaml
# Type basic-auth obligatoire (CNPG 1.30).
# Le même mot de passe est répliqué dans applications/n8n/n8n.secret.yaml —
# les deux doivent rester synchronisés (namespaces différents).
##############################################################################
apiVersion: v1
kind: Secret
metadata:
    name: n8n-user
    namespace: postgres-prod
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:0fnv,iv:HjniQcXbgYM2xcngRRi55feuTC9P9G8O44We49bPlN8=,tag:hHcJ+C1wVdBCvyN6epYuOQ==,type:str]
    password: ENC[AES256_GCM,data:EV4W03wCaeGLmYjDykPqbZz3604A521O8TOxz00Bx+dWWIBlhmDQGA==,iv:K8ir4qnauUp1mPqTSbAoPOaPKPmnKoVp+X2U+pF4pAA=,tag:tWhchjYSXlyR1r2HsyZqlA==,type:str]
sops:
    age:
        - recipient: age13945fxf9dmg0sgmy9hteh5tuvlpz90hx3dqx63plf63f4zwhg9ysth6d98
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArTTNneHlZaUFkcWE2aFQ5
            MzQ0MC9MVklBMzh0S2Z1dWRzOGZ4YlZieGlVCjYrQ1NPczdmdzJHVTBHS2t4Umsx
            c0hHc3kvZTlhWXFpV08xeFptQmViUm8KLS0tIFkvbG5XdjFSVXlCcDdTVElTT1dH
            cEFJcURSZ2ltTEZKT2pmR2h0Sjd6NGMKrp+wsgBx3xBLVRGnfhOe0gEJVe2FhHF8
            Wfd/pK73yHZMdpR9nZdXDIiNpfMXkmbTt5+q1Idjj6uc6+QJHh/ESA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-07T09:17:04Z"
    mac: ENC[AES256_GCM,data:y+Ndv4rjiZBJRun/dlkCI+WOPJ2KSJCi0n3FZx+dFlZ/+pkw+7GEM6mNnRzA5lAMvJIfMTIjaf0E1jT3/cOyUNecPHfhU8jRj6tKU16cn6RNw87c18xsC9KcstffrIhikmJzYEEAUvEy/Y9pEqjFnqrApzsILpkiBvnWOXl3eDg=,iv:HfI1SuQ1i46PHB3q9Pps4dQ2E5Ugs7Nz/6j1d+CZArM=,tag:L0Tv/ozCOp5ovrHgC91/wA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
