apiVersion: v1
kind: Secret
metadata:
    name: zitadel-user
    namespace: postgres-prod
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:fxpYKFpT6Q==,iv:S8uXtgAJI8ZW1E7bw6U7WcK0MuDsZg7JauDVJa+XCo4=,tag:w61LEioizyGD0hnzWjhoqA==,type:str]
    password: ENC[AES256_GCM,data:5kLSfZGHkqFGzoBkprfs85tzZzjMIjPRq2vceIbTS5mtbpSb/unO0eqmZX4Lb3PM,iv:3ULggQQ8Xf/buWDctvgc/G4992uf0F+gui4FOdsDy70=,tag:Z0tXfld0m/PT5UJqyWHchQ==,type:str]
sops:
    age:
        - recipient: age13945fxf9dmg0sgmy9hteh5tuvlpz90hx3dqx63plf63f4zwhg9ysth6d98
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4YmNKZ2dBRFBPMGdYM1Fp
            UHRrZ0UxSVBLYjhlWHV1ZWtpZ1llY3JydGpFCjBvRmhmbkVubWo2ZGJPMWhvYi9w
            cGdablhwZGpPWEtLNnY0WFFwVWJNQUkKLS0tIFkzWHZXaWgrYlJZQ1lTK0N5L3Rk
            cGlHM1RGWGZ1R1hHMGR2QVF3YW0wdU0Kh9lZgKxpB39huYjGNpBhmMiKbDExKPMJ
            /bV7QZnDWkWc0sI1dzWbdi/6wORmacrYAGcwR95uOOgu0oVDLlv2DQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-09T19:53:25Z"
    mac: ENC[AES256_GCM,data:ii0PxSGsMQMdmUPPIT1jHp5X3YZp0+tra63f5oKlclV1g93Jsw3hnkmHYKSY7LKb1MoSb1xJOa3QBweAEEY9uZ9DQEgUzWTk0UJMBZ35/ruEXpKSQHbK8SFizVhY0ZLzHJbEy3j+/WWOlrUKm/P+keKvsxVIflWlI7GotJPXZbs=,iv:YQP2J1DXJfxj40avIjsEJnFUs88w0JjCYrrlL8gbQe0=,tag:oB7tRCPwUCxyhh3wY9xUsw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
