apiVersion: v1
kind: Secret
metadata:
    name: cdn-git
type: Opaque
stringData:
    ssh: ENC[AES256_GCM,data:RnBnRfo3V33SIsJOFml6r0Slqnl0B9E/OO7x5o7Qm6l7hAMmn6j2oLJehml2YBOG4GJPKEha+8EQFI54pzDrbv4RoZYmcJC4PQ3HX7SvXV60X8nWqbw8JOWflDT7L+EUN908xIe7gCGXb7Ef0FNag1M1CqToPQ6hLGXDv0GEv2coAF4zx9Y4d5DRggO8j3JbKQQmLZj7AV1biK5VgK/YOTduCn/c7wK71jVNNRYVbGxD+wAqbcX97VDXJOa19QIx71l5nVyDIpDA3pMNhJ6u/h5yeflWlxgtSD3Ds0PdqfMojZKIc9Tv1r3CZyviiNw+cooeVa9QmYl+oZk9cR3ZiJVzoRQ389CpScZCvPhSpQSXGXYh7n4g6s9mdI7c9tAaWTgTFQnYl7iZrslrG5mxuCysEiz4YXyJitRyLk8sTuBRqk3v8oPqaykrLFnxe9jyHgJuZxUTq/kJOrtG0XJOO+EN1VkKWi/cbmybZABPrQ/0RCFAvrYlrhuTl7Qhsn9NBJI72vGW7X1g1hJpayJoqjWMVBk3QpgsEsOuFwmKMmw+DAhZxPTE8hpJJJPx0+pj,iv:CurGDAJiXrRISRw+PBqqSl2SKcS9YUtPo84h26rcIhA=,tag:bjF0WoCQ0/yPCmCPQTCAmw==,type:str]
    known_hosts: ENC[AES256_GCM,data:BzLMZRDT7SWJhflVwTDDi4W7Pl7bCQaEs4SlFWIRfamkgUdXV2LkwqVwP6zMDJPQYkR/vSR39FXiw34M2ou8Ddp3QSbPcQXrnNlwf4pLbLXcmBVI8zLxAisnOE6suZCogeCN7BhQE+aItJnBnjILRozud00HJrDRhYkDPw==,iv:PLXquM98gcBm6QnBgYSCrXYFtUVGims2hpvdLgPjuQ4=,tag:ai0lH4VD+dBrdjFPoJwqbg==,type:str]
sops:
    age:
        - recipient: age13945fxf9dmg0sgmy9hteh5tuvlpz90hx3dqx63plf63f4zwhg9ysth6d98
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxVXFXckpKcTBScHl6ZWUy
            aENYWWpRbGw0QnRUc0hEK0JBd1RoaDRzdzFjCk9xam9nNzJmNDVYT1VXMzdKTjRC
            VGkyOXk1M2x3bmM1ZXJLUXNOaXBwaEUKLS0tIFFmYXFOemhRZ0s4ZnZ0cHA3RWxK
            TlVITzJFcVNXaGgxdGV6KzlzdVlrUUUKHqMkexiOytFPxXwRAHeCv30iYL6XympR
            Apens2HhFpo5yDUacwc9vo7hYmm+/7VmzzCp7yriTl50rMyBE0oD8g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-02T06:00:08Z"
    mac: ENC[AES256_GCM,data:IpKNKx51EQGKt/B/W267YE3YgoU7cFoA/JOcBzl2q2itmhDm/dnoQOJlp6KCL7KO3Nb2z2DisMsMA/SMt1vr++hjnaqPF2Eguyb/gKYV4TzUe6a2uTJx1xygYT/RzDsE4LK2Nn5uaZNqI3TEZ9ljKYffgDSQatPDDR2nyCjCQJI=,iv:7dOnEjvseo/cElq5/pY2BoU3gqYvpk6GlTMBexxKCas=,tag:m5lhWPiVw8cArfqFb+B2AQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
