apiVersion: v1
kind: Secret
metadata:
  name: wger-secrets
  namespace: wger
type: Opaque
stringData:
  DJANGO_DB_USER: ENC[AES256_GCM,data:cbJkjg==,iv:TAABGI/7yowJbZjqWvggDv2CE9/rInM0Ou7L1ELSv7M=,tag:ejC/Zy15FP8aoHRvDfFHwA==,type:str]
  DJANGO_DB_PASSWORD: ENC[AES256_GCM,data:9/Bsu1PKs4+3hEY1U1h1xei7wR8=,iv:U/ChJhLkT4PigPKZ5N4G6a6Zj4OmByTz7yTpIhyf6cY=,tag:C611nvBFwRs9jFdIzGsegw==,type:str]
  SECRET_KEY: ENC[AES256_GCM,data:z1EFZznUGB8TmZYA28N7kTGi/VXP62PqTdUJp0RUtVPspdlQmxlGKGIzmYyUDTUqRM1QdptEes2gunVgxREJlA==,iv:ft3u639PkpIhQpFyczCBhWkT++e5wnsg40lt/KQqdaw=,tag:+dKIe1q0MwAZX9/REY+PLg==,type:str]
  SIGNING_KEY: ENC[AES256_GCM,data:dsH0m3BHzDBCGiwrnnz7gQj7fGi2WFW6FINd4bDpzH8Il/5crWlEPBk7jrA=,iv:g8E3eDdsmep4e8DPviH6imnSA9uCKCc1r0ozer8FJbI=,tag:T04YA9PTvimh3KHsqWEyJA==,type:str]
sops:
  age:
    - recipient: age13945fxf9dmg0sgmy9hteh5tuvlpz90hx3dqx63plf63f4zwhg9ysth6d98
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5QkdxYndQa3llU3pkUk51
        UmNZc0hodlhPd2YzSWg0cDU2TDBER05ySmdNCkE3TE9lRTdLVFdwc3NMNEd6TEZt
        VUhvdFZEOGRvbzk0K2xlSTY1WG9UNzQKLS0tIDB1RjhpT1hlcU0rU0RXUVI1b0V2
        c0duT2lCYlUvTUNBN09LWDdaL2c3YWsKPBGmm7pLKRo5Atqm1b8DqfEghPvSUDJX
        A2IYJ2ROxpIVwAuEJQes7pFY7yoDsY1NPToMJBtL9A+iq2RysVYxPQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-06T04:46:10Z"
  mac: ENC[AES256_GCM,data:sFUnQBuzTBDOzm8FNNnEz31fRbFQzlHy/9NWtgIFbqB9b3wTDwXU2H6cEfZubyYw2R5NVLw8PECDagy7HEOlmIoL+CJsgktjMXlXuJAjNrH9yDqW1WGpKIkM4nMU6yDZUcmmq//wlki2Dy02NPasu4Oepv20k8QerfppAVJ/Hhc=,iv:KzWJ/ERZH1nUfQ4cUQrfdL2vS7+6LXoZhdBQ7m/830Q=,tag:sTvuQIav3gk9kWvr6KwCuQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
