apiVersion: v1
kind: Secret
metadata:
    name: ghcr-login-secret
    namespace: temper-dev
data:
    .dockerconfigjson: ENC[AES256_GCM,data:Nz0+oPfmPTy6Ld/5n3oL7MhrxnOdG/QugbLliI5kam2Y7E1sg9mBWo16AwdUDp7zHT3XOJfPXg1k8yo+RzQ3NgZwvJXuFCTDMuNAdpf/xJjXSJpMyYmSQ461sUJ85AxjxaLd6+wxp7bXwjkvu71xWO0pfU/YSaJlpz/lTWvTTN6IgVefcA5xeDLT56yshxku4assn2U/sxb8XlAyppNN9r/r+k9/htVSv8EkIJOlFk374Av7xX3kINzmm5yZOeLqgqHgp56WbbtMTnYBb8+qjlbjrIDFN0ME5nri9kV0mspihVXgwlaLshZzDbL/F0h0yl58wLobBOEGJrcxI+fT5/LeNkM+oxTITcjwwnxmGG8ErozITX9KuZFG7YXjZrUwdlkxMw==,iv:aCwVLi9AFHbjQFMYLq4FlO5KwOjYiPY6oVUTa5opuAg=,tag:bG30uIcFBScGZaiSK3vIyA==,type:str]
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - recipient: age13945fxf9dmg0sgmy9hteh5tuvlpz90hx3dqx63plf63f4zwhg9ysth6d98
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiWmtYTEI3UmRoUkJGMzlP
            cDZiRnliZ212U1V3NHJTbHJTMEppcUpNeVVBCnNMeWE5OHY1aEFDSjFWeXo1RFhy
            bUE4K3NyV1lJTzhpbzB2MDNncXYwSUEKLS0tIDdEckROYkZSTkdWQjl4R1ZKNkNI
            Mkd6RlhaMWxLdXZjWVlOdjE4N3NFeE0KwFNY4EaYMO9Xbe9fm1FmOAInRxgO2uuz
            k1awS+6CW8WH8TFEyZMzfLsMgR+qY6m3gLeQKFRrJpzTb+ZYaXq8gQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-09T04:33:46Z"
    mac: ENC[AES256_GCM,data:Xy9201tuRXPDiAu4VDbusX+TEZyLGxpstUCmY2yPKu9CkmgOFd9zHWikb+EHi2ciTYe6okxlrcU9QfaTImzbZRMAcCX8UMRlJNsoKqxOZVZmISQbJNai0QA1QCcbbRRGu7rL/Gmw5BmF62hWQAZ6nECXxdleTXpKNIM2ID7hqY8=,iv:zdWo/UCXVeGYzq9R79QZUqogTGGkD31o+WTJKPzIl+E=,tag:JfvrnyrEaYs6TLZ1sSGLCw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
