apiVersion: v1
kind: Secret
metadata:
    name: temper-modules-secrets
    namespace: temper-dev
type: Opaque
stringData:
    MONGODB_URI: ENC[AES256_GCM,data:HTbWwsAdh8tNAHTRysdC+Fc9eslN4GoBWLjFSrbd5hneMKzhlvHKwaohzkjOCJUzMaR8bs4YONcp4agFoa7xPA/7Wnp0gLovniznCIf0Jkcg5crkK9Sb3/h+C0skgU+fFAVzpt8dG3Ls2Nq9dptMSDk5GatlvF9Gb6IabURQbExjbjjinEqubTMCslt8NottYXcOd+gqwGX1WQaNcdx7wIERhxHLHOCCpMfUAUlB947yL31IH9VeP9uP/M5T7ucfhCEW4Q4KuaFM9K3agyLOciazyIXHOLDHEkkU0PjScP+L0KtTY8LCIoAG7HJaaxv5kRsKHcG7Bqm6CeSc0shidetTj/KC8hpHijRsDjMRb7wmXNkctE3QI7bNxEobb3d59owwZBv13VZht+fJuzIBWB9m0rtxBlVm8W5bN5P2pb3ZgiNxxlfZ9zr9/2dLud1nVJEca9vnZ2RbXsCH2EwLAQ==,iv:eFRwyomJwy+CytVqKBzj242Y7HvCMuLrxeF79SAUeB8=,tag:pObMxlMEFa1C92kD5L9Nrg==,type:str]
sops:
    age:
        - recipient: age13945fxf9dmg0sgmy9hteh5tuvlpz90hx3dqx63plf63f4zwhg9ysth6d98
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTMytEbCtDbFQybDFpOERv
            MlBDeTNPQ0MyQURvU1YrS0JoaXE1ci9WTVJ3CmRMVXNQaHBhSGlUSDMvM3d6ZWd6
            T2xYSjBDaXoxYXdpSEJiWDRyTFFaQmMKLS0tIFZic0FqZDJiMFRQVFdVMG1pUmlQ
            NkZSYlNUQk9CSEdyNVpDMDlIS3I0VGsK7MA2g2DHSwRiQzg9oYa5lJ5dlWzTw0i3
            ynUOJEE8qIsa4CcjKF2+tL7YcB9GQFb3Awid2AC9rIZ4MSpgl7PzBg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-30T17:18:45Z"
    mac: ENC[AES256_GCM,data:Sm/s0qJJHhuzTjeb7QsQhayGJd5wPAlIJ50ojZ6ljcfELscSgEnf16mQUaJP572xlICikUcS5hlJlM4yaB0LFlkI87ojwK8vcwd70m/L3N7bHwBAqWTsf8uU7avAQcBCBkrXbubQqZZT7URUQjJNduQHUTflLcRJXzONE4BReWY=,iv:+awaOFqcQkbg59GvKWoPI/50DZskhWFkOtBTb0SzWvM=,tag:4ZskTmaxnCuKOPNVTWp6wg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
