apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: temper-dev-ksops-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - 10-infra-secrets.secret.yaml
  - 11-docker-secrets.secret.yaml
