apiVersion: v1
kind: Secret
metadata:
    name: litellm-deepseek
    namespace: litellm
type: Opaque
stringData:
    GEMINI_API_KEY: ENC[AES256_GCM,data:GpK/MnIr4vLMgfB0C+FEr2XTD2qsrGHHuFca3GX7NLdDq+c=,iv:4zTVMNjjLnjMjzLWXZXmfelyMuHZPbXnZ4cQTeCZmiA=,tag:cL+EkfRWzbf/b1YngO33KQ==,type:str]
sops:
    age:
        - recipient: age13945fxf9dmg0sgmy9hteh5tuvlpz90hx3dqx63plf63f4zwhg9ysth6d98
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqL3kzVXZpTlhncEc2YW1a
            S2JSS3FDbGVRMStGWnJ1TnhOenAreHpxNGxZCmVyMXA4K1dXdC9EbnFFUnNzUndu
            U1QrTjB0OXMvWUxxemxkWEhlSy9BbjAKLS0tIDQrMUt1WEFQY0t6c1ZxM2lSSEJk
            U1Q0NmVHd0RoL2ZzMEdMUW1NQ0hWNG8KuGeErjwV61Qgf7aw9nw6m8Q60Sv5r0oD
            ffo8WtisCWEZl/+mRS/jlaQ0zoP+Rkow2b1IoGSVe3+TBFxp4UI4Rw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-10T05:32:27Z"
    mac: ENC[AES256_GCM,data:Y3IRwZHRz6Hxa+FmrfJgAioYf9rOgrkNOHEEOkDF7Aaf8dvRCggRKTtgBGKmvZYWdy697xnno9VE+4Sw1LZJjx1n7HH6q+oCBZr2oMEPMFnUKELhdVhvFtr/Qiw78b1535k6oSPiaSy9w9OZk66M6QqNg9fcb0/QpRuHjq5PWlc=,iv:n+uE0gZTS0e+F42Xhh0u45ZH+efTBHohPSZT+6pn1u4=,tag:ECj7LidMEsBtwuDouf+0mg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
