##############################################################################
# Éditer : sops applications/litellm/litellm.secret.yaml
# Remplir GEMINI_API_KEY / MISTRAL_API_KEY / DEEPSEEK_API_KEY.
# LITELLM_SALT_KEY : ne jamais rotator une fois des creds en base.
##############################################################################
apiVersion: v1
kind: Secret
metadata:
    name: litellm
    namespace: litellm
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:hFVfoH/iHtyHHrEx497cW2rlPqBySxz37AAJt8brbt6omI/jogQ/raVbPrgZ7gFqyxJolHQ9Fnb6w2bdTGnCjS51ciyaZOp7rJID84XXG2atomx1g3A10Hp5qSqyXVrB3HQRSDdJyYXAU6c3nZaHnXvCrciA,iv:Y6ZhTqFZUbYsD8f8czXwH4ueXf7mBKQbpodmIR0DUI0=,tag:ThjKiM8qVs9nOkDOOVL39w==,type:str]
    LITELLM_MASTER_KEY: ENC[AES256_GCM,data:bj1JDlilyJw8Jna8c+IKKOX0cSPCQipwlfhP/QsDeSmnhx4dT8KJth4wSe5ds3PIHtS8,iv:NU6GdFPm2BhLKdFx2vUb7u29rKqKNHzor66Jb/SkSs4=,tag:U7IdzSxRkzq8OHFqhannwg==,type:str]
    LITELLM_SALT_KEY: ENC[AES256_GCM,data:VFEl+rTuUugH39jN2liUtAoDX9LdF0UKfJ30wo7Qm0pcp85lwyypvHtFF1qpUjt3Gcgn,iv:6jPBjurK0Sx/JBCoQrX58WYLdxR8abfKWQG1T319fVg=,tag:XC0q4fV29xV7Lg5XKbWQ6g==,type:str]
    GEMINI_API_KEY: ""
    MISTRAL_API_KEY: ""
    DEEPSEEK_API_KEY: ""
sops:
    age:
        - recipient: age13945fxf9dmg0sgmy9hteh5tuvlpz90hx3dqx63plf63f4zwhg9ysth6d98
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYNldqTG8veFd4Q21ZVTZo
            UXYwckZhNXpMN0NFbDR0NUxhVTNQTFJRbUVrCmdxZytLSGVUSUNvZEp4dUZKM3Y5
            UExrZ1ZUNGVBTXZZaXcxR0Q1TEw4eVUKLS0tIFdCRDdiK1ZSRmw3Sjh1ell3cmZ4
            RXNpRi9DaWVJekNaTGVHd09sRVFTdmsKGnm9VCpFuC6eIycAl6TWLWEhbPsY4xbG
            EOmNrOgpAftIYwjGkF6Hike4i70UlKfC7PmmSwlwCx3BbaRYqmCTfA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-28T06:40:40Z"
    mac: ENC[AES256_GCM,data:4CZARgTV9rRn9NjlHnY0+/m0aMNrTP2Tk0qGY7dzmj5FPSeqDiwQJGEVdLEj3L+ZaWBcKrwqvVqd8Fmk8abjiw/flqiXlEsvC7dXfpZhqsQxr8L1EJNnAJIrr+5kmadLNQojp+b1fbONfQ7KGN4m2S/dcbyxaw7efl5SKSVmOB4=,iv:9xrHvVae93obz3ZAw7FpHAgT3J6b7Nf/udtkpKCxwRo=,tag:BDLEe6oySqWuLq035xWU3g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
