apiVersion: v1
kind: Secret
metadata:
    name: litellm-gemini
    namespace: litellm
type: Opaque
stringData:
    GEMINI_API_KEY: ENC[AES256_GCM,data:OpFGVgfLrZYibcaqoyVPe64D+W28ddG8TKCviulI0ZjvG0hqf8ixRjHUl1pu/pnDpeWtAuY=,iv:Kpidmsy8H9l34EeauuP4ggG0zk10tr/s6RST1rudLso=,tag:76cZe8sQZEIcut+NeMmnjg==,type:str]
sops:
    age:
        - recipient: age13945fxf9dmg0sgmy9hteh5tuvlpz90hx3dqx63plf63f4zwhg9ysth6d98
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzQ1lVY0FTNnZabDBkcWZp
            QWlGYWFUV3Y5ZGRsemFFYitENkh2RDhpSmhzCm5yaHZjL29BaXlidjNBNVpPRXZC
            a01TY2ZwelZGNGY4dmg3Y0k4VnhXUnMKLS0tIGVZYVVxalljMUs0bDUyL1doWHFx
            N0pWUWdoUjVFdTVkUzBjN2FQYSs4RzQK5kewketIb2QlQhwNVh+DRF+OxxsuvJSJ
            hPWWGW/86zU9gYgV5PS9elU7QeYxVrhqUd7iacVANk2NDvL54kLGbA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-08T07:29:23Z"
    mac: ENC[AES256_GCM,data:h82t8Bx4qZI9KMrhhVgOnOCbSJkhfZsAesHdIqcBrR/5l6ArOSbTF9u/Cu9MtIqb7dz7fRKmdFeWhQkrtI5gLzU/v0FcAk6DbOOLJZA7wE6bJl58KRxe5t96tuPN6RRMdEaVEykquV7iEmXpJKVIZNYima+uLKf309J2JS+4h1k=,iv:JO7zKOVzSGObmvXgUUqJmGofUc86h8gAw8OQAjS6r3A=,tag:6lWiM42XarwmG1AskacO6A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
