##############################################################################
# Éditer : sops applications/litellm/litellm.secret.yaml
# Remplir GEMINI_API_KEY / MISTRAL_API_KEY / DEEPSEEK_API_KEY.
# LITELLM_SALT_KEY : ne jamais rotator une fois des creds en base.
##############################################################################
apiVersion: v1
kind: Secret
metadata:
    name: litellm
    namespace: litellm
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:Yep7aD5RFnSH7avNbqjFnBK0/Bs+vMKRUMj9VQzc4p8m08fqkklFF8O6utjVF9rpvXEo4D8rPOwMHrLz+/TDzrJrio3r2Si1k66b8aZST6XPbSATp6JJ7ptBvySEs6tT9HhOSeJ3wNJKSTBTABDdfyokhvqL,iv:iQSx+08jLC3VMoTXBBAiXRmXAXAQML4k8BqESmTNRIk=,tag:zkLyXnxU6DZ4YJV3LxdBDA==,type:str]
    LITELLM_MASTER_KEY: ENC[AES256_GCM,data:qAw+iHVxinUKsPWzYnro8qfWkpmK+qunxtkYxImIRMHefLgvixxwwruf/D7uRimyqynR,iv:hCQ7pttADu1ccbvRa4+WMFoDTJh2l9Bw23nLSYVuW+w=,tag:dhspixqCweo4j6lJue5ehQ==,type:str]
    LITELLM_SALT_KEY: ENC[AES256_GCM,data:QZ6LewhViIzJcbDE2ymhk8pr4kmZdX2ZJej8CueZjs8+xPqIs7oxjFlQsNjGWCPviuRp,iv:J/GFfZkWtOQlazKxbSJKi6+PF42qU11CQrpv92N1t9c=,tag:iykd1XhbyVWVBA43+CDsAQ==,type:str]
    GEMINI_API_KEY: ENC[AES256_GCM,data:sqmCP+fHa8qQwPb6fPWE8QMn0fXgTn4kNruXkEXAXj3QB972ktWGI/kyVaWae/OjsJ2qabk=,iv:QitNQro+4B8bvvbIYrapV/37nzztEMRUHbqxYGzSEhw=,tag:zpfxQRzaQZvrs7JQrV6gDw==,type:str]
    DEEPSEEK_API_KEY: ENC[AES256_GCM,data:9N3i33yafZEXFbdJJwUcH0NbenwHu032qS5c10UZRVNQW4c=,iv:AV4eNkNAQ5JPl6RzSshyfJd7E4RLFSYEemccgKa2uyc=,tag:5G/zKgyCh3VtpNKNoJq6aQ==,type:str]
sops:
    age:
        - recipient: age13945fxf9dmg0sgmy9hteh5tuvlpz90hx3dqx63plf63f4zwhg9ysth6d98
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIMnNyWnh0WmZ0TUl2alhw
            eE1HbXVjV09sMXdHT3lIeUNyemZ0czdTbG40Cm05TUR5Kzk3dGpBSGZRa3BIRXJa
            RjBZWmlFYVByd0I3SGtMaUZlcFBJY3cKLS0tIDl6TFIyYnplTEp4WUtyMFhKSHRn
            TWRyeEY0T00vU3VZMHJjK2dJK1E0RGsKamD61b7iJThS7bwntTKv+SLgGDk1nxcR
            c9JyH35WCpL73KjDDLQ4pjRl/tjZC9k5sUKiSRXtsl30Dz7SKKvB1w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-10T06:03:14Z"
    mac: ENC[AES256_GCM,data:Q3NOWbjMuf0U+A6/kYQSeKqEBAD9OKd+r8V0ymsbsRhoan711AAZR+HWqfpB6ORZyKUPojoxtk4IMRE2iWXPH3Em2vVjyiyJyB4TIH+dCILn9ORNl03TdHosuoWC/yPylqLx5Nex11hAbkgIpYpLYAJfGSYLRWupzsKekW+b/GQ=,iv:bZczblmhQz+srhjNpKL/wrP3y2vlAk1U4sqL9UQJtpY=,tag:CtQluhkE4QwObdqxazvuSA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
