apiVersion: v1
kind: Secret
metadata:
    name: authentik-config
    namespace: authentik
    annotations:
        argocd.argoproj.io/sync-wave: "-1"
type: Opaque
stringData:
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:I9Y42YlaCcaUC/QI8rZlok3oio3leAvb/eTw+39lYuL9JSGiPvtemU3lOhrm+aq+uVZVzSmDyYaJEFDDHGJWmzrIbGrdgPosNluCipjZFat/0StpIRI=,iv:cdY+DMeZxhCmrUll78JyflCHrkgUCYSnmNqC4tO0+xs=,tag:AFns3BiX6nqg+wN/tVGqfA==,type:str]
    AUTHENTIK_BOOTSTRAP_PASSWORD: ENC[AES256_GCM,data:+I+s3XUKDypVqmKaVW2U4kz2hphLfjomzc8N4BO7O7UHssWL1b5Zm4OUCQ==,iv:N96Ev0BOLNp1nswCbZkmP9JJEXmvJ2AGIVvjCFP697o=,tag:UgWLJnsvVIrFU77wdeLSog==,type:str]
    AUTHENTIK_POSTGRESQL__HOST: ENC[AES256_GCM,data:ppoY26TrfTWkgO2mp0J9Q7emOnETSK6+f9tTcMU5J2CyQZ6F8anlhekzyFw4WJqA,iv:DE5yppYs664eL4f+vDy+n7Gb2Tj0efJc54tMSXx/NjU=,tag:aY4fxBUfaB+0h5Uca5mbUw==,type:str]
    AUTHENTIK_POSTGRESQL__PORT: ENC[AES256_GCM,data:mk6R6g==,iv:bxi97w+AVOQjzucBJLiLFb39Kd1sfMgZ2t3R8xH4pm0=,tag:eQHAUW748ilWTmo1jyg/tg==,type:str]
    AUTHENTIK_POSTGRESQL__NAME: ENC[AES256_GCM,data:B/0vqiPqMc3Z,iv:ujiRYm+4/ZqCMBdvWkY1kba8nR1SgjDo5yfxD5lUuIA=,tag:fwmLUvvJB1VVCwAKfeOtOw==,type:str]
    AUTHENTIK_POSTGRESQL__USER: ENC[AES256_GCM,data:0z3iu4/9OeCd,iv:B7n4BMT3OiRHwk64353xIaHht1zBWBw+DdR6+5DkOXc=,tag:dOY/Qe0OqxkpMVIYhI/06g==,type:str]
    AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:TZshjNbAM6i5R7qCTBA6E40+5zqNx8/2vwBGbiI/umG9O7dhIza1ChBoTttv+FuFByNje8hE0YstwCN4p1Utyg==,iv:RSerDDuzxM3RC8fDKvYapWneNzudzSgdTZFW6qwIZ1A=,tag:gCsV8ORLfzkeI9QNS9E8aw==,type:str]
    AUTHENTIK_POSTGRESQL__SSLMODE: ENC[AES256_GCM,data:/7IjvP/cFw==,iv:WNXl1FwSlsau68oY3rHh0oTGF3gAYyMCbxu3drfkcwM=,tag:4eeL1A53Z5wjuixeh4KlPg==,type:str]
    AUTHENTIK_WEB__BASE_URL: ENC[AES256_GCM,data:Xe+dRb+oYuHEOpHmCWgJTzcvr74z,iv:4pnSg2GRLoy/6dUc12wjwortWpweB/6K/VWlazIrsH8=,tag:kXLygJtKwzxCOFzb0B8R2A==,type:str]
    AUTHENTIK_LISTEN__TRUSTED_PROXY_CIDRS: ENC[AES256_GCM,data:ldCahwR7CQpHdRUl,iv:iS522LD0Qe1/SGvKzy/vDwGAfZOFTyb9IR0Ce4oLfbA=,tag:WOMzcoS9LT0FPcmGNLBktw==,type:str]
sops:
    age:
        - recipient: age13945fxf9dmg0sgmy9hteh5tuvlpz90hx3dqx63plf63f4zwhg9ysth6d98
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArTEpORHk2UzdGOW5seHZJ
            UzNVMUo5RjFvRytjY3hBTTRhOGQ4MVR5UUZzCnQwSml6VWxjajg2dUp1S1lJQ3Bw
            aWhqZ1h3VjF5alNQcS81YXE2WUphY1EKLS0tIHVBc1puWVpNbDhLUlpoNnJBeTRs
            TDYwbWRtbGY4YlpKVTlTaUdvem5Sdm8KUjVu+xxi1bn3tGEmcX2O/F+tOia4GmhM
            8iTWOnwtFuEwPDX8y8IHFJpuKcTWuTnOm66kChwgGdB6rlnjmIYsQQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-03T07:14:45Z"
    mac: ENC[AES256_GCM,data:YFuhFy0TteizV2xXxJiRMMT/VhcfTAYIME+kE6d7El8zNfmLoSj6juiyyNw2hHhjJikoOzipZ+9303ny/tSncomtyGFnNFPdCkVm2OPG+NjTGCZb7EP1TeTu40hq7Yf46n0xJOC6jXwocWFrtAiOwk/7TW680RltMcRTjx1A3wc=,iv:gAi1reGc6TlZYpsKKnIvPMQCaWx00PHZ5IqQxO+GNiM=,tag:L6BVH+SqZ6kOXJkos6Axsg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
