##############################################################################
# Identifiants admin Grafana. Mot de passe généré aléatoirement.
#   Le lire : sops -d applications/monitoring/grafana.secret.yaml
#   Le changer : sops applications/monitoring/grafana.secret.yaml
##############################################################################
apiVersion: v1
kind: Secret
metadata:
    name: grafana-credentials
    namespace: monitoring
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:yO7l7Go=,iv:wXWm+vlirTVrqS7x9uwaR6a+nIcgiDR3hnZBu7rvf7U=,tag:8gmZ/kMayY7gTbxLAq307g==,type:str]
    admin-password: ENC[AES256_GCM,data:X42y3M+ogSeLFbm+UtRMrxADYrSPip/Qb2zHMg==,iv:BYjnq29bUlpnC3+Cvouxyq3wOorkx39idyQLY18G/nM=,tag:DeB8yLHnWcYA3MPPG9/13A==,type:str]
sops:
    age:
        - recipient: age13945fxf9dmg0sgmy9hteh5tuvlpz90hx3dqx63plf63f4zwhg9ysth6d98
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCWGR1Y09BSW5CbmRHSDVT
            emlRNWlmek9tM2FjSGVXOEVrK3VCWjdqbGxVCjJEc2pNVkRJV2FsTjN3V0pjdDYv
            M2NBNjBpY0dWR2JFbzdDTVhkRzJxekEKLS0tIHduZEVXOEh0SjZVY2hCM215VXJx
            S0xkcyttaVZwcHZGajNnOUpQRU1EMzQKMXLs+QhiON3m3ighkJRQYXAQx7Mrw5Hr
            npMkacZLe/5jldbbANHAmtPR1G3KVhZ4gclptzJQyc7kNt2xslcBNA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-06T11:38:21Z"
    mac: ENC[AES256_GCM,data:XURSnjsEmjpmEGZgcX1kfM4dnVNz9I75wcE9UIeH04zduumTjNzvWurVGRERpyJYUiEX2Cl6/xDVzV2QgarTKjjvutTtf+a45bE6cutDkozd5vUgL9ssdLrlxPGb9cv7R/j6p7i0GZPaxQGSXe4DZggkCF5Wn6PjhYwL/5o/J6c=,iv:U5OHM855UwcW2FAxlExFTT9yHtPajHD9T56afmppwQI=,tag:/7oT3J7f+zEgSS64R4HRZw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
