apiVersion: v1
kind: Secret
metadata:
    name: ovh-credentials
    namespace: external-dns
type: Opaque
stringData:
    application-key: ENC[AES256_GCM,data:vt3c/rO4WxTEr4z/NTdsnA==,iv:icw/2YHEJtJ2Q+mdkrSKFRTmfmZawuPk2aCBSOywJ9M=,tag:RQ19frD3ylrdDuBDrD1Iqg==,type:str]
    application-secret: ENC[AES256_GCM,data:hsOJlEPgNgLAD/jdCVwgiY7g0EvwOu2bBecmjCI5U8I=,iv:0bohkr5guHzU6LY21g8ViYtCBetkwcAIGw/RIduRFx8=,tag:veq1MkPMF6vl/9YLDBaiIA==,type:str]
    consumer-key: ENC[AES256_GCM,data:3/UpDIaNxwqX1uSWTGmyYTmBTWIQBBaBT3RsHVBRquA=,iv:d7FE2Wc8/j4eFleOaS4gxUwDR1YH7aCN5Uz/3DqmEXk=,tag:hBtNIH+qHGHJkpULreXwWg==,type:str]
sops:
    age:
        - recipient: age13945fxf9dmg0sgmy9hteh5tuvlpz90hx3dqx63plf63f4zwhg9ysth6d98
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBydjRpNXE5dy9JbFVpK05k
            U3I2RW5mbWh4RkY0NGorU2lzSnV6RXhmZjFzCmpuSDBLVWtVUFdEZHVZTnJFT0Zr
            S3VlclVET2JWbjZldDFhNHluT2Qxc2cKLS0tIGxObHFuenZNeXUyMkFkdzNiZVBC
            QlNjYmw4UVdnVmNwbFk2ME9nb29XS1kKduujoc3oggezKnJi0ti6g6ItqRqqB96P
            vwqkemZgnRLhrAE4gzoCylsVwKIghRAfG6NMs3lb7HsGdxTc+zeP6g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-16T06:51:57Z"
    mac: ENC[AES256_GCM,data:sYgeCaCLWmbF1eR1tzDfEegr6rrJNsK2KH04TraKVPo9J6XsT8ZBpRG1T+VNm6uEbQFDToz2nv4YZelT/bGwsXHuJA1fyXo6JOE/AOA1UdU+DXFJG1iFxAs3Nfmm9ZdeaSUCQ+F7Eub+9+goO1gDnE0R0TkR6mDDYF2FKcXp2R4=,iv:OXBwiwuNirjemYF4q1rr2dalBLqKm22aULpLgpguSFg=,tag:7FEJJq9tZbpX+px7wIwsSQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
