apiVersion: v1
kind: Secret
metadata:
    name: ovh-credentials
    namespace: external-dns
type: Opaque
stringData:
    application-key: ENC[AES256_GCM,data:4MEVwNJ54yLyjQF724PF9A==,iv:Zbk6J0cRRRYwPztoowbBPOplWi4sUP+a0mVTf4CU0as=,tag:2riUX/9DclQ40L3n8dL7Rg==,type:str]
    application-secret: ENC[AES256_GCM,data:HZxUrAF8B+g4NwOVYo2PBYEJy9dRvElOOsD22+DgqqE=,iv:3IZ0jRgc5UasBYvApm1u0S1SlJIiqyiqakQ9iA2ibnU=,tag:dZdps5urIvB5I79FjgwhdQ==,type:str]
    consumer-key: ENC[AES256_GCM,data:3OdCIRC0o7MIrs6bG4TRDe0kr7PBSJDud81mHBjeT0s=,iv:eiXEI0cO20y6kjO5DiiJv4/1Vv/6ey8umjHS/qyHvlA=,tag:DQjZVCpLBKkhA1uo/7ZlYg==,type:str]
sops:
    age:
        - recipient: age13945fxf9dmg0sgmy9hteh5tuvlpz90hx3dqx63plf63f4zwhg9ysth6d98
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBudlI4dnlmcEhEajVmUDVL
            U0ZtK3pKM3laUmsydG9DMGczbUlEYVdrTmdBCmt5bXFrdW5ESmxnTUpOaEdnR2F6
            UitBWUxDSHhtUmd2V2tueEliYzRYZFUKLS0tIFpFaWNHZVFsVFUycm1VQ1dLSTdQ
            Ym5pbG9zQXRPV0s5bVZLWStidmViaGcKB/ZPrvHR5+e2bpcVISK53oBzb52ZRKai
            XazSVH8OGNOj1eO5nzdZ/eSeLv2S8Fry0lJiHWmDGMivIGHdX24aOQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-16T06:59:16Z"
    mac: ENC[AES256_GCM,data:qwhZr/AYCTZH24/dgQfwKDQ1L5PZhtD1Fk5CIACAnBEVHDXwFlKSwhFj1YC3nAxMFmiQfXIx0AmXgRyHeIfMhPlHZeHMnk6yp7dS/gRnbER48egxnw5rx8IA5CWE+1fn3cn/fvi0JxXtSDIhzLNtTxXw+4fs0VCt3Ots1RcDbN8=,iv:50md0glgUDVQCYhRDa9vXJuYu2WVowEoz5mN+K+DF8Y=,tag:QW6ABfJdh8ixQbCXhiB9jw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
