resources:
  - ../../base

labels:
  - includeSelectors: true
    pairs:
      app: gemma4-26b

namePrefix: gemma4-

configMapGenerator:
  - name: llm-server-config
    literals:
      - MODEL_PATH="/models/gemma-4-26B-A4B-it-Q4_K_M.gguf"
      - CTX_SIZE="262144"
      - PARALLEL_SLOTS="2"

# patches:
#   - target:
#       kind: Deployment
#       name: llm-server
#     patch: |-
#       - op: add
#         path: /spec/template/spec/containers/0/args/-
#         value: '--chat-template'
#       - op: add
#         path: /spec/template/spec/containers/0/args/-
#         value: 'gemma3'
