apiVersion: v1
kind: Secret
metadata:
    name: ghcr-login-secret
    namespace: temper-dev
data:
    .dockerconfigjson: ENC[AES256_GCM,data:RQQXW0NgQCVn4MxpyP9uPtZIxGrei/3CHULIFQMicZIuKfpuKM6GUx/t6vw6VfvYB74qKj+/JiOaPTQhis2HrwQ4cUt14ZhFtRK4lEvj1HjY93re7I9R60djpPn/ABSGwfHXNXW9vOZibpa8HwwNrowBgSaiAsmZC14b4vUZYdsOke9q6TvgKVFpgQ5JueO4Z27jET9wwsCrJZGlgK7YlEUsufgIb0GJs/WfAcNYELTl9pSNK0sOaiKlgbwRMvJkqKeM7g7iCLci3WZcS8uLKHXO9euxqDx+0CkQ5Hz+//Pg6UfIkDD9hPa2wQSenRgt+o9jOTvQKTGim1Izzmk1qHuTICFFsKuNOeepWvv+Of1Hh55JdbyNQLw1Az/5HOMnRDLUlQ==,iv:GxbryBo+FLSspKiw8iDTKs1/selw+uW2T6SwJ9GHcPY=,tag:d45rHYLjA32L6cP6fRGiWA==,type:str]
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - recipient: age13945fxf9dmg0sgmy9hteh5tuvlpz90hx3dqx63plf63f4zwhg9ysth6d98
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYamRaWlBGZ1hjTUVPaVJy
            OE5zdVFIUllkZmpvRVNNYXZ1YTN2MGd2bHhRClRMWWc1Y2NxNmErR0hSUWNhWVZM
            anRNZFV4RVd3VGF0RmxmWnZ3dXlZbTgKLS0tIGxwZG81RE43cm5VK0pvc2xKSTln
            UFl1STR4RGZLbXhpVUE3SlFRWFVBOWMKYc0KZmXY3Y2Myw2vA6v1WISXLn7diTvN
            2XJVV58bgK9dJQQOHQ8OWfgFxl3IBNBuOzydkqHjmrPTmR5dLm6r8A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-09T04:34:01Z"
    mac: ENC[AES256_GCM,data:5t0C7J4E8qhZye9keXswl4ms8SFkS8Hx91Ua+l9DaEynh8pdVBCS5t/rN9EjsNqAQ2mHbt0H2e03meqzSj/dMMuyJYgRKnu/k4/9rVhlRXX7lIlr17FRyOWe2wE1nDWKLPDmOiIah1t4zFx1EsS6vXqam45xOZmzxFV/pdzzjis=,iv:wAk/qYqPy/ONs9JpcOIjPmTNIJ7K4kzIyDcskTnH3Eo=,tag:8epaXCotvqIG/wywIChsJg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
