##############################################################################
# Identifiants S3 utilisés par PBM en DEV → RustFS in-cluster.
# Doit rester synchronisé avec applications/rustfs/rustfs.secret.yaml.
##############################################################################
apiVersion: v1
kind: Secret
metadata:
    name: mongo-dev-backup-s3
    namespace: mongodb-dev
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:990sIScOx6S4p94ndyvImH4e,iv:vJYh5kh+rRbrCzA/A7TwUc8QG94/dOyBZFyN8ucpCkc=,tag:ZkaLX63UWt89WDGXC8/fNg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:rnXAk2l5+o+w1PqkPHq5JvBFIk5Tf14wxFWAl2YBqyNHc7b+o7GJ4g==,iv:xQuIACypamM/nkv72cK98hfGOau0PthuPvOgPYLmAFw=,tag:RuOtzZG6SL8TtMC44Ce8nQ==,type:str]
sops:
    age:
        - recipient: age13945fxf9dmg0sgmy9hteh5tuvlpz90hx3dqx63plf63f4zwhg9ysth6d98
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkN0x2WU04YWNTeUJpR2Z0
            clNMdmdKYWY1NjIrUFNjNWJyenJXenhNN3ljClJYd1l0dVl6ZEVvSzVNVldJQjZE
            THZDMnIwUU1HY1dad3N3OGs4VlNsVzAKLS0tIFlUdkZwUTdtSXhoR1NYOUpJV09B
            SDZqOVduQk5sSEFkR2EvWEtDOG5QOWsK7WLy+8eQus4Ce2yWPZOtyd1MVEBaIXgJ
            hqAqeO6QRsa9QrSNOB2R2YqEPZ1BBAwImjVxyGQXeTEcNnZ6uSi9dg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-06T11:38:21Z"
    mac: ENC[AES256_GCM,data:BDSH4J62CiukVExlOW1PiPUduqgAKlGzjztW/xFGD+cWk5srDbRy1+Ld0jLlwGatd+C0z3t0vmAX1oTxEHmaJYHeRR1Tm9iUmwLUpxpDOLWmjWXNRwgupWbBANiFNCkK40pkqkEWJTyIXZbqGZoFDrtzHP0Gx+kugQI6k1f/ibI=,iv:39/4SeBEqbp4EzMp/oWkOdJ4dPTRyHigZzzjw9BCm6M=,tag:aC/TkaCv7Gh0+u+ssKitDA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
