##############################################################################
# Utilisateurs système du replica set MongoDB dev (consommé par
# spec.secrets.users). Mots de passe générés aléatoirement, alphanumériques
# uniquement pour rester sûrs dans une URI de connexion.
#
# Éditer :  sops applications/mongodb-dev/mongo-users.secret.yaml
##############################################################################
apiVersion: v1
kind: Secret
metadata:
    name: mongo-dev-users
    namespace: mongodb-dev
type: Opaque
stringData:
    MONGODB_BACKUP_USER: ENC[AES256_GCM,data:6pLYhcTh,iv:4NxrLA0PrfxkI0FIJ/VtT0SWFeO7LUA7wDvIYEIp9jg=,tag:jgZf9mXCHRv+xMyDuE3uqw==,type:str]
    MONGODB_BACKUP_PASSWORD: ENC[AES256_GCM,data:9EFXpHsdI5SzjGodXZMWVDzTGaf0zdTaZdbKd/ame+Q=,iv:q2WilfFMoNEANp0HUgo8DTPG0IBCMzUmHYaq8uidGxc=,tag:GOCC/DBrnUDZAM2TH+Ynaw==,type:str]
    MONGODB_DATABASE_ADMIN_USER: ENC[AES256_GCM,data:nrEGvyxubGnmdXOgmg==,iv:UhRjNSzJ3S2btfj9oCfJh06e6YC4kVVX6Dlyt/qLXtU=,tag:NHcKUyTCZjSdcax2+5ygRg==,type:str]
    MONGODB_DATABASE_ADMIN_PASSWORD: ENC[AES256_GCM,data:kvFn0QPZblLRpptTlXYbFEkRfKevYNlduZervIvftf0=,iv:aaK1w3doHXY4WvlRPGmhbT/0jXMT+yikbje1l3kmdFc=,tag:/wUUh0sXExLK5zTLYKvhag==,type:str]
    MONGODB_CLUSTER_ADMIN_USER: ENC[AES256_GCM,data:4QJtgGSgbEVcRW64,iv:yvCtRvY0qXdluTeildUtyRBde+KVdOMFWJNQ2KHQJKk=,tag:vGSGSwgTgAUqbDQ3yf13pQ==,type:str]
    MONGODB_CLUSTER_ADMIN_PASSWORD: ENC[AES256_GCM,data:1tpBEulj9Ku33Ic+JcG+1QNK7Q54yg73F0WmBvVwh0A=,iv:o3RgzrU+oUMBAfzuES+VZsZwey6tQ7H07YUpVq+rR+Y=,tag:DogX3n7Te1IbUuWVsP1lbA==,type:str]
    MONGODB_CLUSTER_MONITOR_USER: ENC[AES256_GCM,data:o/pcDQrXiGkWFoAekQE=,iv:9pEvUCXqPJJnIYQQyiMMSvOgmeu3A4K/LBkvIWqYIUo=,tag:jGxsuN5CJ6P+uPEYfjpoBA==,type:str]
    MONGODB_CLUSTER_MONITOR_PASSWORD: ENC[AES256_GCM,data:x+alO6bcuBASgxq0IQH1XAbIHb49OWczlnWgc95D90s=,iv:WxtIY2o8WVTPkvoreuFqebNCN6ZKJZfnZJOseM4nYXA=,tag:EjshV6odJG1406JJCBghuA==,type:str]
    MONGODB_USER_ADMIN_USER: ENC[AES256_GCM,data:4DEgOBhkq1Rk,iv:J02jT8zFsUtEfvZcYlQfmgKndFogdTDN3WKHn7G78cY=,tag:OksSvY18yKZ8cp44FUiSAw==,type:str]
    MONGODB_USER_ADMIN_PASSWORD: ENC[AES256_GCM,data:2ehL2wLwUJWe3bFEzRNNnxooMxoyHz1Z4+UNszfkDVY=,iv:j3/IKvTDXaz4FO7Nfb4ge61nQLseUQNHAwRoOpperjk=,tag:Qjfcng+W2yMmYnZUFl4XoA==,type:str]
sops:
    age:
        - recipient: age13945fxf9dmg0sgmy9hteh5tuvlpz90hx3dqx63plf63f4zwhg9ysth6d98
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCcnF4UXNuZWRCU2twakZn
            U3Awa0M4ZC9udlAyTjJjQlZ0bWh6cElsWUhNCmdiY09MR095alJZclJKK1dWVm5Z
            UnRUMGhUTU45ZVlSTUtRMy9wR1FzQ2sKLS0tIGxSMDZGNmg1TGFZR0lGdnFTbTg5
            MUlmSHFwVWJqT2RYN2FOckMvRHdFS0UKoan1v5qG9W/ayzx0FFTQ4RVRZ2VZYfO6
            Z82OVwEyyDbO3c5UUHnxi+oSmDR8rOsVhAKLGmta725j2kZ5FfILAQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-06T11:38:21Z"
    mac: ENC[AES256_GCM,data:WjIEfBnescvetGSL2QsOnKJ5PX8j90OjSrgWv75DQ9v2sptamoL5eBRbwHw75Q3RGilFhm9/Gx9KkkVZ6hRLDdnZ/M7plJa1XgPLvcHnCWBSXN4jh/+XUaB1htIOT4kFL/6XkZLlkR431iqXEcH8L/TNm9Eq7EC8Wn4g1rB3Nyk=,iv:IUaYl3QECS+G9vDnlIWqLBJZi+KOk8M1iKE5aO487ZM=,tag:3b7ue2Gu9r3dDndNzSonhA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
