##############################################################################
# Mot de passe de l'utilisateur applicatif "app" sur la base "appdb"
# (référencé par spec.users[].passwordSecretRef dans 10-psmdb.yaml).
##############################################################################
apiVersion: v1
kind: Secret
metadata:
    name: mongo-dev-app-user
    namespace: mongodb-dev
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:x4dKaX5gxFpbB20OY//aa2Bg4mq0vGbWrqWElHdGKRU=,iv:G/ehDOZ4j+fvw5JIZxv3hivUvQJ+5lEUWro6WdKl+dg=,tag:lPVZ54y+cCxfFasw5DV4Bw==,type:str]
sops:
    age:
        - recipient: age13945fxf9dmg0sgmy9hteh5tuvlpz90hx3dqx63plf63f4zwhg9ysth6d98
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGcHF2TXpzWFJwV0NSWTZj
            Zk5RZCtLc2JsQkNmV3g3Q051MGp4T2liM25FCml2RkRlcFlteVNEYU9kMU5ENFow
            eVRoVTJUcmZBd2xESGtwK2xuNFVadWMKLS0tIGFOc3oxWnR0N2hLbG9xNEcvT2Zk
            cUhFSXhrSm9INVArTk5US001TDhxZjgKB/J8KaYzJ4CQZLFSf5KabvIxyP3vIpfH
            nTRUizTqjYHrdM4ABGf1rXrN90CyM/gnJ62H305dH/GS61g0ruG8Ng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-06T11:38:21Z"
    mac: ENC[AES256_GCM,data:SF/0NHNm/k62AJYmWv2E3Tzvl4kA+b8Z0Fxzvhfbcb9vPWq69LJa9Yn+cHZCtKZEjfstjxQa/TmAjJvlHzHTzka7pwdYoFXfc8LJ47jHhbhigZZ8AsdVkVQQIc4xsoRPLVm//bQmrVEjw2deOX53OpSxZswtoEDka7oJNDbcauc=,iv:jCT4jecJSFtx6NksamuTV+hOT8sdEjOqQQ6xVvEYXzg=,tag:yPx6wdpEpM0ng0TAP6aBpA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
