##############################################################################
# Modèles téléchargés manuellement sur gmk-ai-master.
##############################################################################
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-ai
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ai-models-llm-pv
spec:
  capacity:
    storage: 200Gi
  accessModes: [ReadWriteOnce]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-ai
  local:
    path: /home/michael/models
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values: [gmk-ai-master]
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ai-models-llm-pvc
  namespace: ai-stack
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: local-ai
  resources:
    requests:
      storage: 200Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ai-models-whisper-pv
spec:
  capacity:
    storage: 20Gi
  accessModes: [ReadWriteOnce]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-ai
  local:
    path: /home/michael/whisper.cpp/models
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values: [gmk-ai-master]
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ai-models-whisper-pvc
  namespace: ai-stack
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: local-ai
  resources:
    requests:
      storage: 20Gi
