##############################################################################
# ComfyUI (ROCm) — Génération d'images
#
# Image : kyuz0/amd-strix-halo-comfyui:latest
# Backend : ROCm 7 (AMD native GPU compute)
# Modèles suggérés :
#   - SDXL Turbo (~6.5 Go) : rapide, 1-4 steps
#   - HunyuanVideo 1.5, Qwen Image, Wan 2.2
#
# Interface ComfyUI sur le port 8000
##############################################################################

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sd-server
  namespace: ai-stack
  labels:
    app: sd-server
    component: image-gen
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: sd-server
  template:
    metadata:
      labels:
        app: sd-server
        component: image-gen
    spec:
      # ── Scheduling sur le noeud Strix Halo ────────────────
      tolerations:
        - key: "dedicated"
          operator: "Equal"
          value: "ai"
          effect: "NoSchedule"
      nodeSelector:
        gpu-type: "strix-halo"

      # ── Conteneur principal ────────────────────────────────
      containers:
        - name: comfyui
          image: docker.io/kyuz0/amd-strix-halo-comfyui:latest
          imagePullPolicy: IfNotPresent

          workingDir: /opt/ComfyUI
          command: ["python", "main.py"]
          args:
            - "--listen"
            - "0.0.0.0"
            - "--port"
            - "8000"
            - "--output-directory"
            - "/outputs"
            - "--disable-mmap"
            - "--cache-none"
            - "--bf16-vae"

          ports:
            - name: http
              containerPort: 8000
              protocol: TCP

          # ── Accès GPU ROCm ─────────────────────────────────
          # /dev/dri + /dev/kfd requis par ROCm
          volumeMounts:
            - name: dri
              mountPath: /dev/dri
            - name: kfd
              mountPath: /dev/kfd
            - name: models
              mountPath: /opt/ComfyUI/models/checkpoints
              readOnly: true
            - name: output
              mountPath: /outputs

          # ── Santé ──────────────────────────────────────────
          startupProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 30
            timeoutSeconds: 5

          readinessProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 15
            timeoutSeconds: 5

          livenessProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3

          resources:
            requests:
              cpu: "1"
              memory: "4Gi"
            limits:
              cpu: "4"
              memory: "24Gi"

          # ── Sécurité ───────────────────────────────────────
          # privileged requis : SELinux bloque les allocations mémoire HSA de ROCm
          securityContext:
            privileged: true
            runAsUser: 0

      # ── Volumes ──────────────────────────────────────────
      volumes:
        - name: dri
          hostPath:
            path: /dev/dri
            type: Directory
        - name: kfd
          hostPath:
            path: /dev/kfd
            type: CharDevice
        - name: models
          persistentVolumeClaim:
            claimName: ai-models-diffusion-pvc
        - name: output
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: sd-server
  namespace: ai-stack
  labels:
    app: sd-server
spec:
  type: ClusterIP
  selector:
    app: sd-server
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
