##############################################################################
# Open WebUI — Interface unifiée LLM + Image Gen
#
# Se connecte à :
#   - llama-server (port 8080) pour le chat LLM via API OpenAI
#   - sd-server (port 8000) pour la génération d'images via ComfyUI
#
# Open WebUI peut tourner sur N'IMPORTE QUEL noeud du cluster
# (pas besoin de GPU)
##############################################################################

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: open-webui-data-pvc
  namespace: ai-stack
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-webui
  namespace: ai-stack
  labels:
    app: open-webui
    component: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open-webui
  template:
    metadata:
      labels:
        app: open-webui
        component: frontend
    spec:
      # ── Scheduling sur le noeud Strix Halo ────────────────
      tolerations:
        - key: "dedicated"
          operator: "Equal"
          value: "ai"
          effect: "NoSchedule"
      nodeSelector:
        gpu-type: "strix-halo"
      containers:
        - name: open-webui
          image: ghcr.io/open-webui/open-webui:main
          imagePullPolicy: IfNotPresent

          env:
            # ── Connexion au LLM (llama-server, API OpenAI-compatible) ──
            - name: OPENAI_API_BASE_URL
              value: "http://llama-server.ai-stack.svc.cluster.local:8080/v1"
            - name: OPENAI_API_KEY
              value: "sk-no-key-required"

            # ── Désactiver Ollama (on utilise llama-server directement) ──
            - name: OLLAMA_BASE_URL
              value: ""

            # ── Connexion à la génération d'images (ComfyUI) ──
            - name: COMFYUI_BASE_URL
              value: "http://sd-server.ai-stack.svc.cluster.local:8000"
            - name: ENABLE_IMAGE_GENERATION
              value: "true"
            - name: IMAGE_GENERATION_ENGINE
              value: "comfyui"

            # ── Divers ──
            - name: WEBUI_AUTH
              value: "true"
            - name: WEBUI_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: open-webui-secrets
                  key: WEBUI_SECRET_KEY

          ports:
            - name: http
              containerPort: 8080
              protocol: TCP

          volumeMounts:
            - name: data
              mountPath: /app/backend/data

          startupProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 12

          readinessProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 15

          livenessProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 30
            failureThreshold: 3

          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "2"
              memory: "2Gi"

      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: open-webui-data-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: open-webui
  namespace: ai-stack
  labels:
    app: open-webui
spec:
  type: ClusterIP
  selector:
    app: open-webui
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
