apiVersion: v1
kind: Secret
metadata:
    name: sd-server-secrets
    namespace: ai-stack
stringData:
    HF_TOKEN: ENC[AES256_GCM,data:jVDhe2cH5S4udUeuCyruuiz57t8Zm1q/kkKGqCjQ+Wts+4083Q==,iv:Li2LFQeHELciiT2+O9q65L1Sf5RBZyMHYsNGOVH40Kc=,tag:UmeKmnTS9LU9ronye+ml0w==,type:str]
sops:
    age:
        - recipient: age13945fxf9dmg0sgmy9hteh5tuvlpz90hx3dqx63plf63f4zwhg9ysth6d98
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCRTVGcWdmYnJjZUMxQ3RX
            RS9tcWczUUxVUndlZWR2SlVHQnhMNTk5UlRjCldJZ1hhaVZwQjN3VjVQYU91STVz
            V2xTai93Ly9CTHFIcWszcEZTbTRzTE0KLS0tIHBuZXR2L0VSbnBLNzMxSUw3TUZC
            K25KdFo5UUJieE5Pa2REOXhYNW0zM0EKdTmYJGjBAUe/v60gpnHFEOnup3a88e/+
            WOC0i3cfF2Xw+Ht4A96rl6yZu58Yed4BT6dwUxfjq0eJkyJHAzXMGQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-17T10:13:31Z"
    mac: ENC[AES256_GCM,data:XB9UL4sJWLyA/xkxYXVXV/p/mDHJGbQhGQBLECFovWhawNWovpGBEEEZ9j/xrp+bYXQDNs0L9aTA+WwKoZTXjlzmSNiQIQfI8UQM6vPG4XIBQaoK0mzStWNT8TbuI5S4QjED7aduj7NJsR3bUQYC6eZRrV9gATFm9JsZOWY7WxI=,iv:BHQVaUXvLFGQoskHDrljQvvl6ndVLk+yIDpmQv3QIAk=,tag:+a8OOtrGJblhr2fWjZhOhw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
