resources:
  - ../../base

labels:
  - includeSelectors: true
    pairs:
      app: nomic-embed
namePrefix: nomic-

configMapGenerator:
- name: llm-server-config
  literals:
    - MODEL_PATH="/models/nomic-embed-text-v1.5.Q8_0.gguf"
    - CTX_SIZE="2048"
    - PARALLEL_SLOTS="4"