apiVersion: v1
kind: Secret
metadata:
    name: frp-token
    namespace: frp
stringData:
    token: ENC[AES256_GCM,data:2Tzkvw5QBwyx1+thNPrySkmQRsdGkf0/zJJXlKlg,iv:SCz4mtqeimCwsdfwP9KkclBBU/USKWwk0BkFLmWFBHk=,tag:vx8iagXNClG7qahDmi9IkA==,type:str]
sops:
    age:
        - recipient: age13945fxf9dmg0sgmy9hteh5tuvlpz90hx3dqx63plf63f4zwhg9ysth6d98
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwend3bWp5bFk5YjlqYXhh
            WFFFTnd5K2t6ZXIrSmkzRWxtYXRYL0dxbVNZClpzT0k1U3I4RUZMMkh0cTFjbWZz
            ZWJyTktBVDBOSTdPdXd2dHYySHJwSTgKLS0tIFdXYTNRM3BvQUhxYTZ5WkpFenho
            ZFEyRmtyakhPRDloc1RBc05Yc1prVjAKYjHavQ1ZTEVELliyVauzZKJkr6n7mALv
            StIeKMQnNaviXo/PWP2ohDX/WiINGU8CnlC9rSdJ/kaFDe4C9A9+vw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-12T18:29:45Z"
    mac: ENC[AES256_GCM,data:bbqMofKoBhntKWLkS4+ys3YTnBNywbL3/HwoDRe369TZCqZ/+QA15X1pbuNsMlFKfQqVwk1BI8IZKLkkfOl/cuWRp97nLvmKPgxqRhd9lBP9XFR30NN1S2iBHpWGV2MPxppnLBcO4NjtMdjzbxbkV/1RrUDD65Nt0nSmR/ELFAE=,iv:hAX6CAIQ/xKUJS0S2HC1t7h5JKw4q0wQFw2WwL1G8as=,tag:mz/SXNvJ6WLp7zQAWVooMA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
