##############################################################################
# n8n.home.dohrm.fr est déjà dans le DNS Headscale (10-dns-sync.yaml).
##############################################################################
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: n8n
  namespace: n8n
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - host: n8n.home.dohrm.fr
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: n8n
                port:
                  number: 5678
