# KSOPS generator — déchiffre les secrets SOPS au moment du kustomize build
apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: secrets-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - n8n.secret.yaml
