apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: searxng

resources:
  - 00-namespace.yaml
  - 10-config.yaml
  - 20-valkey.yaml
  - 30-searxng.yaml
  - 40-ingress.yaml

generators:
  - ksops-generator.yaml
