##############################################################################
# Secret SearXNG. Éditer : sops applications/searxng/searxng.secret.yaml
#
# SEARXNG_SECRET signe les URL de l'image proxy et les link_token du limiter.
# Le changer invalide seulement ces jetons : sans conséquence durable.
##############################################################################
apiVersion: v1
kind: Secret
metadata:
    name: searxng
    namespace: searxng
type: Opaque
stringData:
    SEARXNG_SECRET: ENC[AES256_GCM,data:j5cuye/hHS7DohQX534bleGcmwnN0YtFTNGV7do0IGrX4e5SRHADCtm6jYDCnH5G0429tYbOMctADJL5FOQ3jA==,iv:JbuUUpFWVLldMpoyBrH/pIlcLjPgfio4rvX/PNi0BP4=,tag:kcZMgJY0X4ebsEKeNdJATg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtWkc3OFB3NzI4RHlxbVpI
            M21HZHFPK2pXMGRySzU3b2Y0UGcrQ3A4MnpJCkF0QndabEIya2VqUWdFWXhNVzUz
            SWNiNHRXd0tpVlNvZ1RicHpuak9vR00KLS0tIFBYYlZaV1dpTXF0RmsxMjl5cERM
            MEUzaWRmRzFWUUlJUFd3QlJUczR2QWsKOKhlC1JQKS+t2E6Kwiv+l4+cZfw07qtv
            h+FuI66YQOksWMLMlVR4kjBEs2HiIlxAOyog8+FKMUwnPJb9FHRzPQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age13945fxf9dmg0sgmy9hteh5tuvlpz90hx3dqx63plf63f4zwhg9ysth6d98
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-28T04:34:23Z"
    mac: ENC[AES256_GCM,data:Qm9jotfYT54wul9yXS6/JnB6kkL5MxS6vCs/LY6TCcCfd26juwfVdwoUqBZbhbHtjKAW07MAPqDsX8CyNWntE2uK5U/9GzJNzn83ZX3Y/mvsz5dn4w3H/tuFpqkTI1ZMKj8H3ysArmRHFKJrwGencvBuWSlK8Cv2nsYHOJTU0fI=,iv:qsCdRbq9EVOGkvCbuXIYKyM9oKg8G4BGrvLtKrevZhU=,tag:1Eo32TmJxgW4bHObcwwdIA==,type:str]
    version: 3.13.3
