##############################################################################
# Mot de passe de l'utilisateur applicatif "app" sur la base "appdb"
# (référencé par spec.users[].passwordSecretRef dans 10-psmdb.yaml).
##############################################################################
apiVersion: v1
kind: Secret
metadata:
    name: mongo-prod-app-user
    namespace: mongodb-prod
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:Zct1Ck3jQd90ckTVQbAIc2HX0mt7hr/e03JSwPuTiOU=,iv:y8/Ul2p6CjYYyZrztcuaAXAgGp+UHGlbZJf7nYfPfRQ=,tag:5IHTW7p8l7DB55EleDss4w==,type:str]
sops:
    age:
        - recipient: age13945fxf9dmg0sgmy9hteh5tuvlpz90hx3dqx63plf63f4zwhg9ysth6d98
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEalk4clBQSTZRUHRVaHc4
            SjdZZzJsTWxVNWFWTDVENFh1YWJHMFdWbVdNCmFvc1pvRkMwSUY1ZHJVMjMzNjFs
            YkJuUVFyNFh5WTF3SldiNlRITGU3eWMKLS0tIGtBTy84RXh1by9Tb2JSdmJUN2hv
            anRuWDczSHdlajhmN0FIUnp6RjlIVWcK/rB34jyUgQ9CJ0Elpgv978zafq5pRJlQ
            jsvgXmsxQ4a7gQo3djk6FIvivzo9RU6pSB7kmbj2Mnkb4M5M17rn5g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-06T11:38:21Z"
    mac: ENC[AES256_GCM,data:dXc9BwdkkMJz3y/UBf9UAU4Vmw/gvh6LrohmFrTEsnc6gFLBJgu7PY8vkEpj/gP1UCw6BQN6OexCqwjhqEKEcva5nVpUfVn1pUlWunoPlvvJgmoNdXIpXzyDcObHaBwF8cut/zvX6fMkaL5TLDHj3YFQj1d6zsF4JpDvbGsqq9o=,iv:BlzEDW6H+lhrlEdv3e8Uh/I3JZl2kMnDwwX+RMmB9S8=,tag:IFhCpO5Tm7xKWvhGHtjrvw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
