apiVersion: v1
kind: Secret
metadata:
    name: mongo-prod-temper-modules-user
    namespace: mongodb-prod
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:JNT2BGQXPdGGjFfofW5sV4BYy4kXMqKrPUrty9bcxCdSUuSkx6JAjTZm0D9ph/PlBs1ntSGX344pXTJv00Gauw==,iv:n04+QfXh0HiuwJnx8CGG3wUISVuk1NagNkCJYKbsRxw=,tag:l7bFFt7jfvlHZ2glHe97dg==,type:str]
sops:
    age:
        - recipient: age13945fxf9dmg0sgmy9hteh5tuvlpz90hx3dqx63plf63f4zwhg9ysth6d98
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKRUJsOVYzSlB5b2d2ZVpT
            UzRjaExpRkpTbm9UMGQ5NUxVc01ocklXM0c4CmJ1Z1ZPeTNrTkpIOHFwNUpJMS92
            d3I3TWZLZ0plWWpTKzRKMFBHOHlROTQKLS0tIEExbGJQc0xNUFRnekFMa0svMGg1
            aXdlUDBmQU8yOHNGL0dBODBnZTk0bFkK4QBxi2b3lpuSZx1SUJidjFZQGwZSu7ds
            13T1LYmWEdvKomFxBNnUrEnRxwBMspFMFxZmhTKMdP3xY2v9GuuFrg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-30T17:18:45Z"
    mac: ENC[AES256_GCM,data:jzQBMKgvMSdKe1inwCO9IuxM2VZQz5mRx8HC8QGINQjxR/oVEN8YCNE8TcDFeoR9DMS5BUE8KFFUTlOndKmx4bGuVqpVf387EP83hq9HGgXoxbH8S+rMguq9VNMZTp2Q6/WpzHAZn5xE3VsJIEVu9FaqRa1VoU4vpEyxYtydL5Q=,iv:eCUKR1PqWOE6qGOaNBHVoPt/Nx/nVweUQjB1KMAUN/I=,tag:ge7a3SGZ17Xyf28IuZBkeA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
