##############################################################################
# Utilisateurs système du replica set MongoDB prod (consommé par
# spec.secrets.users). Mots de passe générés aléatoirement, alphanumériques
# uniquement pour rester sûrs dans une URI de connexion.
#
# Éditer :  sops applications/mongodb-prod/mongo-users.secret.yaml
##############################################################################
apiVersion: v1
kind: Secret
metadata:
    name: mongo-prod-users
    namespace: mongodb-prod
type: Opaque
stringData:
    MONGODB_BACKUP_USER: ENC[AES256_GCM,data:+iC4poNK,iv:FarPFgmWFu33QV3DqzhDCE9R38vrQ+Vxt3TBlc4ixPg=,tag:yhMMYBSA9OtgkkookfqttA==,type:str]
    MONGODB_BACKUP_PASSWORD: ENC[AES256_GCM,data:LrId2DemlYXkY5xJG1Jw6oXKFbc9Ilk+pHZmJ8QlJw8=,iv:ZRHsQxosFtQ1MDewFih8RavodUNmkIMkNgFjv4xheDs=,tag:xjMTGaV1aD8lq1YPZmFZSQ==,type:str]
    MONGODB_DATABASE_ADMIN_USER: ENC[AES256_GCM,data:jhgubYPZ5rUro9JiYQ==,iv:tu46ngFTe8v/MC9asqDXU1sQwOCaGTxlz85UE2P8vOQ=,tag:J2cM3mW3nu38+nEDtp3ydQ==,type:str]
    MONGODB_DATABASE_ADMIN_PASSWORD: ENC[AES256_GCM,data:1jbaqSusxzg9l6egUdq21skwK9fBxsTOdOVTaHesLlg=,iv:Ukn46CJqQCBje4uB+BhuhqFvwajouATT705bY1Yr9h0=,tag:joiuFxUovXobe3ekjQBqNw==,type:str]
    MONGODB_CLUSTER_ADMIN_USER: ENC[AES256_GCM,data:117262Bn2dLk0lLP,iv:PwvywCwq1a3znAUBIN7CCJFAnY90YFjV4f/rr5e9vCI=,tag:VPNb2p550IJuKk+e6cQMag==,type:str]
    MONGODB_CLUSTER_ADMIN_PASSWORD: ENC[AES256_GCM,data:gMo5WIAUXBdS5sP00MCejkYfjmM6CD1j94RWjE3KPns=,iv:eTH2l3Mh6ptQay9brnwLWxOTCSgij9uiTBqsYxqPPnE=,tag:CJBV35Gn38Og8hjuWhXJbw==,type:str]
    MONGODB_CLUSTER_MONITOR_USER: ENC[AES256_GCM,data:VevzXEWbzh6dVf9hetM=,iv:ELwvmrwUmsnnLpn1Ly/h4EhkC9BiUieAw6S2X3IyPNI=,tag:lgpKzRzeqy29lTBDmfDpqA==,type:str]
    MONGODB_CLUSTER_MONITOR_PASSWORD: ENC[AES256_GCM,data:yIQp5ArZZVkUKGvRZFYIk3yNAbD3GGmQSpFg7t9pvCM=,iv:H59sXPolqYfL1p/BnILuWhYgSBnvZ98+HkEUB1iv664=,tag:vTJLjQ+UQmbLEZB6ckSDeg==,type:str]
    MONGODB_USER_ADMIN_USER: ENC[AES256_GCM,data:U1BM8YqV/Kvg,iv:v/NUf6Zj6t+HInj0CqP3ytrR3iIxXiRE8AO8Hs4MYjw=,tag:fzXu5Img1bsGErNN04HOmg==,type:str]
    MONGODB_USER_ADMIN_PASSWORD: ENC[AES256_GCM,data:bPzTCwmQsJOa9jfkxJv0Ib2B44cWyv4UIMvrXKoV6Js=,iv:VQFbE4ub5x43men8p7i8wWI1Fx0MErsABiVvJaK8sSY=,tag:/Pr1cD1417pI6KVuksebSA==,type:str]
sops:
    age:
        - recipient: age13945fxf9dmg0sgmy9hteh5tuvlpz90hx3dqx63plf63f4zwhg9ysth6d98
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUOUlaSGZVKzM1TGcxeWxq
            QzJhMHR4V3hBQ3pDczA4V1BjbWxKL25kTDBjCllhbkFOYU9xRGZ6YW5yQUJYaVFh
            cTFGclVmVWdnb2FsbnNQRE1UcWVpZlUKLS0tIHVnb0VzRkVsNFhKdGszRUYzbitD
            bmxaaTg0NEw4RDR4RHI2TWVUSlY1YmsKaHfcfYbLCDBjhz+hQ06EOhO8BglDWuu4
            i3sRP0wYubi3L3lypIIpD4mTyUwRI1wtRSCHzIhYcCnzP9vH1L8kpw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-06T11:38:21Z"
    mac: ENC[AES256_GCM,data:EYOHfAaPhgSTnSOFb8yDOyvfkolp/r0fXs+WibGwhdFdWBAr5wwt73RlE5+Ws7UFJ8D+DYLjjtoVV5s9OsrAykgAM2XWMhYh98u8fCq3KKkAG1ASv88Do6u+wM3Biil5m06J+8WwvoysN02sJjKnpY1PYe3Fznglwq9Zxi8jY7E=,iv:QHgioCBwZ6OaJ/mDb+RjNv9G40bMP1z6xugYFDIISWo=,tag:K1a0qGgVg1iJlvju6TLKBA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
