apiVersion: v1
kind: Secret
metadata:
    name: openclaw-secret
    namespace: openclaw
stringData:
    gateway-token: ENC[AES256_GCM,data:pb3d8laCZrNR,iv:k+jPjJStAcNllWyNHuY+OdFJ2mK3L7wtRhDebgUr16Y=,tag:d+mwmDX4e/sbFUdPVO+Cuw==,type:str]
sops:
    age:
        - recipient: age13945fxf9dmg0sgmy9hteh5tuvlpz90hx3dqx63plf63f4zwhg9ysth6d98
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZRzJtTzFuNjJBK2kwOElk
            NmExcEZZS2ttSHR3SkxKSk5hRjMyNWh0bjBzCkRNZjRMTDhvVERFRW1BNUtBVFRm
            Qy94aE9veWZqNUlWQnVwaENJNVRCNUUKLS0tIEdiM3BNUk1WU3p1TUZxNzNEcmNt
            VzdLb3lUWkFzVzVhKy9ndGZoYTB0QkUKFcDnmefyxekhOnf5OfmFVItfn1dE8KwV
            d0Il4xhBVO4FB4Vz3KkJU9Bt0S7ULyIKzSQrsk7//xnbUn6qdDKqTw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-19T15:02:42Z"
    mac: ENC[AES256_GCM,data:OIDQcaFdqH+X3XNCpsiSTnEe6/WZaU2NKg31r7Vu7l72pzGcpIYjMoXw4Qb1A+PoGf2rlDIiBfFNjjKNHjbYKpjMQg3cx+PCOz/Rgqsi+97M4iRUIZHZ9Nx6nAqBu56nuuK+flw8if2m99DaJJ+MgU4knjQbwSjYg8GiqAy/PqU=,iv:YYV9pyXRJYbCyydKQ+KZISzl/zUCBjz+zgkHWB0BZIE=,tag:uY2wq3D/mugZo9S5Sx90hw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
